// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CourseworkPastPaperApplication2.Server.CourseworkPastPaperApplication2.CompiledModels
{
    [DbContext(typeof(PapersDbContext))]
    public partial class PapersDbContextModel : RuntimeModel
    {
        static PapersDbContextModel()
        {
            var model = new PapersDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PapersDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
