// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CourseworkPastPaperApplication2.Server.CourseworkPastPaperApplication2.CompiledModels
{
    public partial class PapersDbContextModel
    {
        partial void Initialize()
        {
            var classTeacher = ClassTeacherEntityType.Create(this);
            var assignment = AssignmentEntityType.Create(this);
            var @class = ClassEntityType.Create(this);
            var paperResult = PaperResultEntityType.Create(this);
            var question = QuestionEntityType.Create(this);
            var student = StudentEntityType.Create(this);
            var teacher = TeacherEntityType.Create(this);

            ClassTeacherEntityType.CreateForeignKey1(classTeacher, @class);
            ClassTeacherEntityType.CreateForeignKey2(classTeacher, teacher);
            AssignmentEntityType.CreateForeignKey1(assignment, student);
            PaperResultEntityType.CreateForeignKey1(paperResult, assignment);
            PaperResultEntityType.CreateForeignKey2(paperResult, student);
            QuestionEntityType.CreateForeignKey1(question, assignment);
            StudentEntityType.CreateForeignKey1(student, @class);

            ClassEntityType.CreateSkipNavigation1(@class, teacher, classTeacher);
            TeacherEntityType.CreateSkipNavigation1(teacher, @class, classTeacher);

            ClassTeacherEntityType.CreateAnnotations(classTeacher);
            AssignmentEntityType.CreateAnnotations(assignment);
            ClassEntityType.CreateAnnotations(@class);
            PaperResultEntityType.CreateAnnotations(paperResult);
            QuestionEntityType.CreateAnnotations(question);
            StudentEntityType.CreateAnnotations(student);
            TeacherEntityType.CreateAnnotations(teacher);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "7.0.2");
            AddAnnotation("Relational:DefaultSchema", "public");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
